@startuml
'https://plantuml.com/class-diagram

entity Person
entity Authority
entity Product

Person --{ Authority

entity Person {
    Long id
    String username
    String password
}

entity Authority {
    Long id
    String name
    Long person_fk
}

entity Product {
    Long id
    Long name
    Double price
}

@enduml

