
spring:
  security:
    oauth2:
      client:
        # class ClientRegistration in oauth2-client
        registration:
          github:
            client-id: 97c23f4437bdf7d3077c
            # Normally, this secret should not be committed, but here it does not matter
            client-secret: afa68c881bf950db8e049dd1297bd9f507b9e82f
